### ISSUE TITLE
Fix paging doesn't always work

### ISSUE THREAD

**Issue by aorin** [luomus/cms#2]
With user `KE.341` (satelliitti), the paging doesn't always work, there's duplicates and missing items. For example when fetching the documents with query `deviceID:JX.1370383` and using the default page size, it gives the documents on three pages. The last item of the first page is the same than the first item on the second page (`JX.1427247`). I'm not sure if it always happens with this query or if it varies with which query the problem occurs.

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the getSearchBody method in StoreSearchService to use a search_after approach for more consistent paging results. This should eliminate duplicates and missing items when paginating through search results.

You can review changes in this commit: https://github.com/jjyutm4532/luomus-lajistore-2/commit/252ebf9e671a8e461fed1ec1119322d7a6706262.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by MLumme** [comment]
In addition of sorting elastic search by meta-created date it now also uses elastic _id in sort, which should result in consistent sort order in separate paginated queries. Deployed to store-dev and prod.
